// <auto-generated />
using System;
using MASsenger.Infrastracture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MASsenger.Infrastracture.Database.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("BaseUserChannelChat", b =>
                {
                    b.Property<int>("ChannelsJoinedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelsJoinedId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("BaseUserChannelChat");
                });

            modelBuilder.Entity("BaseUserChannelChat1", b =>
                {
                    b.Property<int>("AdminsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsManagedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminsId", "ChannelsManagedId");

                    b.HasIndex("ChannelsManagedId");

                    b.ToTable("BaseUserChannelChat1");
                });

            modelBuilder.Entity("BaseUserChannelChat2", b =>
                {
                    b.Property<int>("BannedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsBannedFromId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BannedId", "ChannelsBannedFromId");

                    b.HasIndex("ChannelsBannedFromId");

                    b.ToTable("BaseUserChannelChat2");
                });

            modelBuilder.Entity("BotUser", b =>
                {
                    b.Property<int>("BotsJoinedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BotsJoinedId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("BotUser");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseChats");

                    b.HasDiscriminator<string>("Type").HasValue("BaseChat");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("BaseMessages");

                    b.HasDiscriminator<string>("Type").HasValue("BaseMessage");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BaseUsers");

                    b.HasDiscriminator<string>("Type").HasValue("BaseUser");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.Bot", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseUser");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Bot");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.ChannelChat", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseChat");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Channel");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.Message", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseMessage");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SenderId");

                    b.HasDiscriminator().HasValue("Message");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.PrivateChat", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseChat");

                    b.HasDiscriminator().HasValue("Private");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.SystemMessage", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseMessage");

                    b.HasDiscriminator().HasValue("SystemMessage");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.User", b =>
                {
                    b.HasBaseType("MASsenger.Core.Entities.BaseUser");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("BaseUserChannelChat", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.ChannelChat", null)
                        .WithMany()
                        .HasForeignKey("ChannelsJoinedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASsenger.Core.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseUserChannelChat1", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASsenger.Core.Entities.ChannelChat", null)
                        .WithMany()
                        .HasForeignKey("ChannelsManagedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseUserChannelChat2", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("BannedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASsenger.Core.Entities.ChannelChat", null)
                        .WithMany()
                        .HasForeignKey("ChannelsBannedFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotUser", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.Bot", null)
                        .WithMany()
                        .HasForeignKey("BotsJoinedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASsenger.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseMessage", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.BaseChat", "Destination")
                        .WithMany("Messages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseUser", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.User", null)
                        .WithMany("Blocked")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.Bot", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.User", "Owner")
                        .WithMany("BotsOwned")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.ChannelChat", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.Message", b =>
                {
                    b.HasOne("MASsenger.Core.Entities.BaseUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.BaseChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MASsenger.Core.Entities.User", b =>
                {
                    b.Navigation("Blocked");

                    b.Navigation("BotsOwned");
                });
#pragma warning restore 612, 618
        }
    }
}
